### ISSUE TITLE
“Trained models” 是否方便提供一个百度盘下载链接

### ISSUE THREAD

**Issue by FredHuang16** [WangWenhao0716/ISC-Track2-Submission#1]
如题～

**Comment by WangWenhao0716** [comment]
链接: https://pan.baidu.com/s/1xDtfhdqDRJzADfvrbeSSOg  密码: v50e

**Comment by FredHuang16** [comment]
> 链接: https://pan.baidu.com/s/1xDtfhdqDRJzADfvrbeSSOg 密码: v50e

多谢！ 能否分享一下生成训练集的下载直链 （https://drive.google.com/file/d/1Ianqo1TS3Idx-211oWNANoZJ94WVgx6N/view?usp=sharing）？

**Comment by WangWenhao0716** [comment]
> > 链接: https://pan.baidu.com/s/1xDtfhdqDRJzADfvrbeSSOg 密码: v50e
> 
> 多谢！ 能否分享一下生成训练集的下载直链 （[https://drive.google.com/file/d/1Ianqo1TS3Idx-211oWNANoZJ94WVgx6N/view?usp=sharing）？](https://drive.google.com/file/d/1Ianqo1TS3Idx-211oWNANoZJ94WVgx6N/view?usp=sharing%EF%BC%89%EF%BC%9F)

这个成本太高，我们目前没有资金将数据传过去；建议使用多核心（如100核心）加速数据集自动生成，耗时不超过1小时～
